/**
 * Delisted fixture — frontend-only stand-in.
 *
 * No delisting data exists in the catalog yet: there is no status-history
 * table, and nothing persists a last-confirmed date or an end state. Every
 * field here is invented so the surface could be built and verified ahead of
 * the schema.
 *
 * dependentModels / dependentPapers are deliberately null throughout. The
 * ingestion that would produce them (parsing model cards and papers for
 * dataset references) does not exist. Do not populate them with plausible
 * numbers to make the Dependents mass metric demoable.
 *
 * Replace wholesale when wired to live data. Nothing in src/components/graveyard
 * needs to change: components take a DelistedField prop.
 */
import type { DelistedField } from './types';

export const DELISTED_FIXTURE: DelistedField = {
  records: [
  { slug: "atlas-news-v2", name: "Atlas News V2", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 69, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 1381, versions: 5, endState: "gated", lastConfirmed: "2023-08-12", dependentModels: null, dependentPapers: null, x: 500.5, z: 154.2 },
  { slug: "pile-law-v2", name: "Pile Law V2", publisher: "LAION", platform: "huggingface", coverageTotal: 74, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 32185793, versions: 1, endState: "superseded", lastConfirmed: "2026-01-08", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: 398.9, z: 148.1 },
  { slug: "ledger-code-pairs", name: "Ledger Code Pairs", publisher: "BigScience", platform: "huggingface", coverageTotal: 25, coverageBand: "minimal", license: "ODC-By-1.0", sizeRows: 71655, versions: 1, endState: "unreachable", lastConfirmed: "2023-04-27", dependentModels: null, dependentPapers: null, x: 100.6, z: 225.3 },
  { slug: "stack-chat-curated", name: "Stack Chat Curated", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 37, coverageBand: "minimal", license: "Not stated", sizeRows: 23300363, versions: 6, endState: "withdrawn", lastConfirmed: "2023-09-02", dependentModels: null, dependentPapers: null, x: -64.8, z: 216.4 },
  { slug: "quarry-edu-dedup", name: "Quarry Edu Dedup", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 76, coverageBand: "extensive", license: "MIT", sizeRows: 62742749, versions: 9, endState: "unreachable", lastConfirmed: "2023-07-29", dependentModels: null, dependentPapers: null, x: -367.4, z: 344.9 },
  { slug: "open-chat-subset", name: "Open Chat Subset", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 74, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 173857850, versions: 7, endState: "withdrawn", lastConfirmed: "2026-06-08", dependentModels: null, dependentPapers: null, x: -581.2, z: 217.3 },
  { slug: "common-web-abstracts", name: "Common Web Abstracts", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 90, coverageBand: "extensive", license: "ODC-By-1.0", sizeRows: 66317, versions: 3, endState: "superseded", lastConfirmed: "2026-04-14", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: -691.8, z: 47.7 },
  { slug: "corpus-fin-instruct", name: "Corpus Fin Instruct", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 41, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 131520, versions: 9, endState: "superseded", lastConfirmed: "2026-06-13", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: -544.6, z: 20.9 },
  { slug: "mesh-audio-mini", name: "Mesh Audio Mini", publisher: "MLCommons", platform: "direct", coverageTotal: 33, coverageBand: "minimal", license: "ODC-By-1.0", sizeRows: 40216587, versions: 8, endState: "superseded", lastConfirmed: "2026-07-10", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: -327.7, z: -172.2 },
  { slug: "quarry-image-instruct", name: "Quarry Image Instruct", publisher: "Together AI", platform: "huggingface", coverageTotal: 65, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 1542, versions: 6, endState: "unreachable", lastConfirmed: "2026-06-19", dependentModels: null, dependentPapers: null, x: -106.8, z: -279.6 },
  { slug: "common-chat-filings", name: "Common Chat Filings", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 44, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 11348, versions: 7, endState: "gated", lastConfirmed: "2023-10-05", dependentModels: null, dependentPapers: null, x: 61.3, z: -215.8 },
  { slug: "open-bio-filings", name: "Open Bio Filings", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 54, coverageBand: "partial", license: "Not stated", sizeRows: 8620, versions: 9, endState: "unreachable", lastConfirmed: "2024-03-27", dependentModels: null, dependentPapers: null, x: 450.6, z: -89.0 },
  { slug: "mesh-news-subset", name: "Mesh News Subset", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 45, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 7248, versions: 9, endState: "unreachable", lastConfirmed: "2023-06-04", dependentModels: null, dependentPapers: null, x: 605.2, z: -47.1 },
  { slug: "atlas-bio-mini", name: "Atlas Bio Mini", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 44, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 1332, versions: 7, endState: "unreachable", lastConfirmed: "2025-10-10", dependentModels: null, dependentPapers: null, x: 522.1, z: 163.0 },
  { slug: "common-law-filings", name: "Common Law Filings", publisher: "LAION", platform: "huggingface", coverageTotal: 6, coverageBand: "minimal", license: "Apache-2.0", sizeRows: 117171481, versions: 7, endState: "unreachable", lastConfirmed: "2023-06-08", dependentModels: null, dependentPapers: null, x: 376.5, z: 195.7 },
  { slug: "corpus-multi-xl", name: "Corpus Multi Xl", publisher: "BigScience", platform: "huggingface", coverageTotal: 86, coverageBand: "extensive", license: "CC-BY-NC-4.0", sizeRows: 2973, versions: 8, endState: "unreachable", lastConfirmed: "2023-10-17", dependentModels: null, dependentPapers: null, x: 150.3, z: 288.8 },
  { slug: "common-bio-crawl", name: "Common Bio Crawl", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 7, coverageBand: "minimal", license: "Apache-2.0", sizeRows: 586736491, versions: 9, endState: "gated", lastConfirmed: "2023-06-19", dependentModels: null, dependentPapers: null, x: -47.3, z: 190.1 },
  { slug: "archive-web-crawl", name: "Archive Web Crawl", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 14, coverageBand: "minimal", license: "MIT", sizeRows: 6494884, versions: 5, endState: "superseded", lastConfirmed: "2025-10-03", supersededBy: "atlas-bio-v3", dependentModels: null, dependentPapers: null, x: -422.8, z: 330.9 },
  { slug: "atlas-web-mini", name: "Atlas Web Mini", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 59, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 3399, versions: 6, endState: "gated", lastConfirmed: "2026-06-09", dependentModels: null, dependentPapers: null, x: -653.5, z: 210.4 },
  { slug: "open-news-pairs", name: "Open News Pairs", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 85, coverageBand: "extensive", license: "Apache-2.0", sizeRows: 56879, versions: 1, endState: "gated", lastConfirmed: "2025-05-16", dependentModels: null, dependentPapers: null, x: -659.9, z: 64.8 },
  { slug: "index-law-instruct", name: "Index Law Instruct", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 72, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 6530, versions: 7, endState: "withdrawn", lastConfirmed: "2026-03-06", dependentModels: null, dependentPapers: null, x: -454.9, z: -62.3 },
  { slug: "ledger-law-filings", name: "Ledger Law Filings", publisher: "MLCommons", platform: "direct", coverageTotal: 78, coverageBand: "extensive", license: "CC0-1.0", sizeRows: 794785, versions: 3, endState: "unreachable", lastConfirmed: "2026-07-09", dependentModels: null, dependentPapers: null, x: -212.1, z: -222.1 },
  { slug: "beacon-chat-instruct", name: "Beacon Chat Instruct", publisher: "Together AI", platform: "huggingface", coverageTotal: 10, coverageBand: "minimal", license: "ODC-By-1.0", sizeRows: 1469641, versions: 5, endState: "withdrawn", lastConfirmed: "2026-05-26", dependentModels: null, dependentPapers: null, x: -117.5, z: -356.4 },
  { slug: "beacon-code-crawl", name: "Beacon Code Crawl", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 90, coverageBand: "extensive", license: "CC0-1.0", sizeRows: 242925, versions: 2, endState: "unreachable", lastConfirmed: "2025-06-27", dependentModels: null, dependentPapers: null, x: 131.1, z: -216.4 },
  { slug: "index-image-pairs", name: "Index Image Pairs", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 60, coverageBand: "partial", license: "MIT", sizeRows: 9067707, versions: 1, endState: "superseded", lastConfirmed: "2024-11-22", supersededBy: "corpus-news-v3", dependentModels: null, dependentPapers: null, x: 462.7, z: -57.2 },
  { slug: "common-fin-subset", name: "Common Fin Subset", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 7, coverageBand: "minimal", license: "CC-BY-NC-4.0", sizeRows: 55116152, versions: 9, endState: "superseded", lastConfirmed: "2023-10-13", supersededBy: "mesh-multi-v3", dependentModels: null, dependentPapers: null, x: 611.9, z: 8.6 },
  { slug: "mesh-math-dedup", name: "Mesh Math Dedup", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 79, coverageBand: "extensive", license: "CC0-1.0", sizeRows: 26052173, versions: 8, endState: "unreachable", lastConfirmed: "2025-09-02", dependentModels: null, dependentPapers: null, x: 473.8, z: 105.3 },
  { slug: "atlas-edu-subset", name: "Atlas Edu Subset", publisher: "LAION", platform: "huggingface", coverageTotal: 15, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 8190, versions: 8, endState: "unreachable", lastConfirmed: "2023-11-25", dependentModels: null, dependentPapers: null, x: 436.4, z: 200.7 },
  { slug: "open-fin-crawl", name: "Open Fin Crawl", publisher: "BigScience", platform: "huggingface", coverageTotal: 74, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 6408, versions: 8, endState: "superseded", lastConfirmed: "2025-10-19", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: 161.2, z: 179.6 },
  { slug: "common-law-subset", name: "Common Law Subset", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 11, coverageBand: "minimal", license: "ODC-By-1.0", sizeRows: 48113, versions: 5, endState: "gated", lastConfirmed: "2023-03-01", dependentModels: null, dependentPapers: null, x: -86.5, z: 176.0 },
  { slug: "lattice-web-pairs", name: "Lattice Web Pairs", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 45, coverageBand: "partial", license: "Apache-2.0", sizeRows: 1676131, versions: 4, endState: "unreachable", lastConfirmed: "2023-05-14", dependentModels: null, dependentPapers: null, x: -405.0, z: 358.8 },
  { slug: "common-audio-captions", name: "Common Audio Captions", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 42, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 920473, versions: 6, endState: "gated", lastConfirmed: "2025-03-14", dependentModels: null, dependentPapers: null, x: -625.5, z: 247.5 },
  { slug: "archive-bio-instruct", name: "Archive Bio Instruct", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 8, coverageBand: "minimal", license: "CC0-1.0", sizeRows: 4789633, versions: 8, endState: "withdrawn", lastConfirmed: "2026-01-17", dependentModels: null, dependentPapers: null, x: -642.4, z: 143.6 },
  { slug: "mesh-bio-mini", name: "Mesh Bio Mini", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 78, coverageBand: "extensive", license: "CC-BY-SA-4.0", sizeRows: 15054138, versions: 5, endState: "superseded", lastConfirmed: "2024-11-20", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: -472.0, z: -38.4 },
  { slug: "lattice-audio-dialogue", name: "Lattice Audio Dialogue", publisher: "MLCommons", platform: "direct", coverageTotal: 70, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 8476521, versions: 8, endState: "gated", lastConfirmed: "2026-03-30", dependentModels: null, dependentPapers: null, x: -304.1, z: -217.2 },
  { slug: "strata-audio-v2", name: "Strata Audio V2", publisher: "Together AI", platform: "huggingface", coverageTotal: 38, coverageBand: "minimal", license: "Not stated", sizeRows: 78900, versions: 3, endState: "unreachable", lastConfirmed: "2023-04-28", dependentModels: null, dependentPapers: null, x: -119.9, z: -243.2 },
  { slug: "beacon-multi-instruct", name: "Beacon Multi Instruct", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 18, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 6702, versions: 8, endState: "unreachable", lastConfirmed: "2026-05-27", dependentModels: null, dependentPapers: null, x: 113.3, z: -173.6 },
  { slug: "ledger-image-subset", name: "Ledger Image Subset", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 50, coverageBand: "partial", license: "MIT", sizeRows: 654189958, versions: 5, endState: "unreachable", lastConfirmed: "2023-12-15", dependentModels: null, dependentPapers: null, x: 435.6, z: -81.5 },
  { slug: "pile-multi-captions", name: "Pile Multi Captions", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 21, coverageBand: "minimal", license: "CC0-1.0", sizeRows: 765284532, versions: 1, endState: "superseded", lastConfirmed: "2026-04-05", supersededBy: "successor-v3", dependentModels: null, dependentPapers: null, x: 587.8, z: -59.0 },
  { slug: "lattice-chat-captions", name: "Lattice Chat Captions", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 85, coverageBand: "extensive", license: "CC0-1.0", sizeRows: 3330732, versions: 4, endState: "unreachable", lastConfirmed: "2024-09-10", dependentModels: null, dependentPapers: null, x: 536.9, z: 64.4 },
  ],
  total: 40,
};
