/**
 * Atlas fixture — frontend-only stand-in for the live catalog.
 *
 * Generated deterministically. Depth (z) is derived from coverageTotal by the
 * spec formula z = 380 - 7.6 * coverageTotal, so the depth channel and the
 * documentation figure can never drift apart.
 *
 * Replace wholesale when the Atlas is wired to the catalog. Nothing else in
 * src/components/atlas needs to change: the components take an AtlasField prop
 * and know nothing about where it came from.
 */
import type { AtlasField } from './types';

export const ATLAS_FIXTURE: AtlasField = {
  nodes: [
  { slug: "corpus-math-curated", name: "Corpus Math Curated", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 62, coverageBand: "partial", sizeRows: 207957525, license: "CC-BY-SA-4.0", x: 272.7, y: 58.8, z: -91.2 },
  { slug: "open-law-reviews", name: "Open Law Reviews", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 31, coverageBand: "minimal", sizeRows: 176006, license: "Apache-2.0", x: 388.5, y: 110.4, z: 144.4 },
  { slug: "atlas-chat-pairs", name: "Atlas Chat Pairs", publisher: "BigScience", platform: "huggingface", coverageTotal: 99, coverageBand: "extensive", sizeRows: 58016859, license: "CC-BY-4.0", x: -55.3, y: 40.8, z: -372.4 },
  { slug: "mesh-law-dialogue", name: "Mesh Law Dialogue", publisher: "LAION", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", sizeRows: 21101484, license: "CC-BY-4.0", x: -57.7, y: 66.2, z: 53.2 },
  { slug: "ledger-multi-dedup", name: "Ledger Multi Dedup", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 25, coverageBand: "minimal", sizeRows: 411665, license: "CC-BY-NC-4.0", x: -161.2, y: 171.1, z: 190.0 },
  { slug: "quarry-audio-subset", name: "Quarry Audio Subset", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 35, coverageBand: "minimal", sizeRows: 5593802, license: "CC-BY-4.0", x: -78.7, y: 77.8, z: 114.0 },
  { slug: "pile-chat-dedup", name: "Pile Chat Dedup", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 54, coverageBand: "partial", sizeRows: 2054, license: "BSD-3-Clause", x: -150.4, y: 63.5, z: -30.4 },
  { slug: "strata-bio-dedup", name: "Strata Bio Dedup", publisher: "Together AI", platform: "huggingface", coverageTotal: 92, coverageBand: "extensive", sizeRows: 2167, license: "ODC-By-1.0", x: -95.7, y: 1.4, z: -319.2 },
  { slug: "index-news-transcripts", name: "Index News Transcripts", publisher: "MLCommons", platform: "direct", coverageTotal: 58, coverageBand: "partial", sizeRows: 520070, license: "ODC-By-1.0", x: -207.7, y: -54.6, z: -60.8 },
  { slug: "quarry-code-captions", name: "Quarry Code Captions", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 85, coverageBand: "extensive", sizeRows: 2915292, license: "CC-BY-SA-4.0", x: -65.4, y: -71.7, z: -266.0 },
  { slug: "stack-image-pairs", name: "Stack Image Pairs", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 35, coverageBand: "minimal", sizeRows: 4904173, license: "CC-BY-NC-4.0", x: -49.1, y: -60.2, z: 114.0 },
  { slug: "atlas-multi-curated", name: "Atlas Multi Curated", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 57, coverageBand: "partial", sizeRows: 103105, license: "Apache-2.0", x: 67.0, y: 4.4, z: -53.2 },
  { slug: "stack-audio-v2", name: "Stack Audio V2", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 15, coverageBand: "minimal", sizeRows: 60037, license: "BSD-3-Clause", x: 162.1, y: -31.5, z: 266.0 },
  { slug: "ledger-web-mini", name: "Ledger Web Mini", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 64, coverageBand: "partial", sizeRows: 8433789, license: "CC0-1.0", x: 223.8, y: -65.5, z: -106.4 },
  { slug: "pile-bio-v2", name: "Pile Bio V2", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 39, coverageBand: "minimal", sizeRows: 59597836, license: "BSD-3-Clause", x: 231.7, y: 22.6, z: 83.6 },
  { slug: "strata-multi-instruct", name: "Strata Multi Instruct", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 29, coverageBand: "minimal", sizeRows: 36999354, license: "CC-BY-SA-4.0", x: 276.0, y: 73.0, z: 159.6 },
  { slug: "pile-edu-curated", name: "Pile Edu Curated", publisher: "BigScience", platform: "huggingface", coverageTotal: 53, coverageBand: "partial", sizeRows: 144482, license: "MIT", x: 114.6, y: 121.4, z: -22.8 },
  { slug: "strata-law-curated", name: "Strata Law Curated", publisher: "LAION", platform: "huggingface", coverageTotal: 49, coverageBand: "partial", sizeRows: 20851793, license: "BSD-3-Clause", x: 114.5, y: 68.2, z: 7.6 },
  { slug: "index-bio-transcripts", name: "Index Bio Transcripts", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 46, coverageBand: "partial", sizeRows: 2908, license: "CC-BY-NC-4.0", x: -22.1, y: 147.5, z: 30.4 },
  { slug: "open-math-captions", name: "Open Math Captions", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 85, coverageBand: "extensive", sizeRows: 19887, license: "CC-BY-SA-4.0", x: -36.9, y: 26.2, z: -266.0 },
  { slug: "common-math-xl", name: "Common Math Xl", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", sizeRows: 7901, license: "ODC-By-1.0", x: -287.8, y: 9.9, z: 53.2 },
  { slug: "atlas-code-xl", name: "Atlas Code Xl", publisher: "Together AI", platform: "huggingface", coverageTotal: 70, coverageBand: "partial", sizeRows: 32774251, license: "CC0-1.0", x: -285.7, y: -41.6, z: -152.0 },
  { slug: "pile-web-dedup", name: "Pile Web Dedup", publisher: "MLCommons", platform: "direct", coverageTotal: 60, coverageBand: "partial", sizeRows: 1366782, license: "ODC-By-1.0", x: -54.7, y: 3.4, z: -76.0 },
  { slug: "mesh-math-dedup", name: "Mesh Math Dedup", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 17, coverageBand: "minimal", sizeRows: 21342704, license: "Not stated", x: -11.0, y: -108.9, z: 250.8 },
  { slug: "quarry-law-subset", name: "Quarry Law Subset", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 28, coverageBand: "minimal", sizeRows: 101909, license: "CC-BY-NC-4.0", x: -16.3, y: -36.1, z: 167.2 },
  { slug: "strata-bio-captions", name: "Strata Bio Captions", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 50, coverageBand: "partial", sizeRows: 310168, license: "ODC-By-1.0", x: 65.3, y: -15.0, z: 0.0 },
  { slug: "stack-law-reviews", name: "Stack Law Reviews", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 75, coverageBand: "extensive", sizeRows: 6871966, license: "CC-BY-4.0", x: 330.9, y: -25.6, z: -190.0 },
  { slug: "stack-multi-reviews", name: "Stack Multi Reviews", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 64, coverageBand: "partial", sizeRows: 817523939, license: "Apache-2.0", x: 122.1, y: 14.4, z: -106.4 },
  { slug: "atlas-image-xl", name: "Atlas Image Xl", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 88, coverageBand: "extensive", sizeRows: 63196, license: "CC-BY-SA-4.0", x: 166.2, y: 70.5, z: -288.8 },
  { slug: "mesh-bio-dedup", name: "Mesh Bio Dedup", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 11, coverageBand: "minimal", sizeRows: 43409, license: "CC-BY-NC-4.0", x: 280.7, y: 76.9, z: 296.4 },
  { slug: "quarry-image-v2", name: "Quarry Image V2", publisher: "BigScience", platform: "huggingface", coverageTotal: 55, coverageBand: "partial", sizeRows: 123756, license: "MIT", x: 90.3, y: 11.5, z: -38.0 },
  { slug: "open-web-transcripts", name: "Open Web Transcripts", publisher: "LAION", platform: "huggingface", coverageTotal: 71, coverageBand: "partial", sizeRows: 287694603, license: "MIT", x: -43.7, y: 112.2, z: -159.6 },
  { slug: "index-law-dedup", name: "Index Law Dedup", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 86, coverageBand: "extensive", sizeRows: 2160437, license: "Apache-2.0", x: -235.4, y: 91.2, z: -273.6 },
  { slug: "archive-code-abstracts", name: "Archive Code Abstracts", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 11, coverageBand: "minimal", sizeRows: 24235839, license: "ODC-By-1.0", x: -331.3, y: 63.3, z: 296.4 },
  { slug: "atlas-multi-mini", name: "Atlas Multi Mini", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 27, coverageBand: "minimal", sizeRows: 8441736, license: "CC-BY-4.0", x: -165.0, y: 36.3, z: 174.8 },
  { slug: "strata-image-filings", name: "Strata Image Filings", publisher: "Together AI", platform: "huggingface", coverageTotal: 28, coverageBand: "minimal", sizeRows: 191101135, license: "Not stated", x: -341.4, y: -32.2, z: 167.2 },
  { slug: "open-edu-v2", name: "Open Edu V2", publisher: "MLCommons", platform: "direct", coverageTotal: 83, coverageBand: "extensive", sizeRows: 16448521, license: "CC-BY-4.0", x: -65.6, y: -113.0, z: -250.8 },
  { slug: "corpus-image-dialogue", name: "Corpus Image Dialogue", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", sizeRows: 24401685, license: "Not stated", x: -127.1, y: -54.8, z: 53.2 },
  { slug: "ledger-web-xl", name: "Ledger Web Xl", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 99, coverageBand: "extensive", sizeRows: 250349979, license: "CC0-1.0", x: -119.3, y: -99.0, z: -372.4 },
  { slug: "lattice-image-captions", name: "Lattice Image Captions", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 73, coverageBand: "partial", sizeRows: 1980, license: "CC0-1.0", x: 105.8, y: -39.7, z: -174.8 },
  { slug: "beacon-math-curated", name: "Beacon Math Curated", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 93, coverageBand: "extensive", sizeRows: 3989225, license: "ODC-By-1.0", x: 335.5, y: -61.5, z: -326.8 },
  { slug: "pile-math-captions", name: "Pile Math Captions", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 86, coverageBand: "extensive", sizeRows: 95179, license: "CC-BY-SA-4.0", x: 312.4, y: -35.1, z: -273.6 },
  { slug: "common-chat-captions", name: "Common Chat Captions", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 55, coverageBand: "partial", sizeRows: 31082946, license: "CC-BY-NC-4.0", x: 91.6, y: 38.8, z: -38.0 },
  { slug: "stack-bio-transcripts", name: "Stack Bio Transcripts", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 47, coverageBand: "partial", sizeRows: 7245, license: "BSD-3-Clause", x: 147.8, y: 95.4, z: 22.8 },
  { slug: "mesh-edu-subset", name: "Mesh Edu Subset", publisher: "BigScience", platform: "huggingface", coverageTotal: 84, coverageBand: "extensive", sizeRows: 24901, license: "ODC-By-1.0", x: 4.0, y: -14.7, z: -258.4 },
  { slug: "corpus-audio-reviews", name: "Corpus Audio Reviews", publisher: "LAION", platform: "huggingface", coverageTotal: 65, coverageBand: "partial", sizeRows: 2506749, license: "Not stated", x: -10.5, y: 80.4, z: -114.0 },
  { slug: "strata-bio-dialogue", name: "Strata Bio Dialogue", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 90, coverageBand: "extensive", sizeRows: 5551101, license: "CC-BY-SA-4.0", x: -237.3, y: 67.9, z: -304.0 },
  { slug: "quarry-bio-dialogue", name: "Quarry Bio Dialogue", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 87, coverageBand: "extensive", sizeRows: 602994160, license: "Apache-2.0", x: -100.3, y: 19.9, z: -281.2 },
  { slug: "mesh-code-crawl", name: "Mesh Code Crawl", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 61, coverageBand: "partial", sizeRows: 17164, license: "CC-BY-4.0", x: -80.2, y: -19.6, z: -83.6 },
  { slug: "beacon-edu-mini", name: "Beacon Edu Mini", publisher: "Together AI", platform: "huggingface", coverageTotal: 25, coverageBand: "minimal", sizeRows: 11895, license: "MIT", x: -174.9, y: -3.8, z: 190.0 },
  { slug: "stack-edu-transcripts", name: "Stack Edu Transcripts", publisher: "MLCommons", platform: "direct", coverageTotal: 52, coverageBand: "partial", sizeRows: 12760631, license: "MIT", x: -222.9, y: 19.1, z: -15.2 },
  { slug: "quarry-audio-dedup", name: "Quarry Audio Dedup", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 23, coverageBand: "minimal", sizeRows: 657152585, license: "Apache-2.0", x: -211.6, y: -63.9, z: 205.2 },
  { slug: "lattice-web-mini", name: "Lattice Web Mini", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 90, coverageBand: "extensive", sizeRows: 2099, license: "CC-BY-4.0", x: 6.2, y: -165.9, z: -304.0 },
  { slug: "stack-web-pairs", name: "Stack Web Pairs", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 54, coverageBand: "partial", sizeRows: 12535988, license: "CC-BY-4.0", x: -23.7, y: 23.2, z: -30.4 },
  { slug: "pile-edu-instruct", name: "Pile Edu Instruct", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 8, coverageBand: "minimal", sizeRows: 11095, license: "MIT", x: 132.6, y: -1.9, z: 319.2 },
  { slug: "strata-bio-crawl", name: "Strata Bio Crawl", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 47, coverageBand: "partial", sizeRows: 1794382, license: "CC-BY-SA-4.0", x: 167.5, y: -37.7, z: 22.8 },
  { slug: "lattice-fin-curated", name: "Lattice Fin Curated", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 70, coverageBand: "partial", sizeRows: 62718604, license: "Apache-2.0", x: 202.7, y: -28.0, z: -152.0 },
  { slug: "stack-fin-crawl", name: "Stack Fin Crawl", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 13, coverageBand: "minimal", sizeRows: 81386255, license: "CC-BY-4.0", x: 230.8, y: 67.8, z: 281.2 },
  { slug: "lattice-code-subset", name: "Lattice Code Subset", publisher: "BigScience", platform: "huggingface", coverageTotal: 28, coverageBand: "minimal", sizeRows: 2711585, license: "CC-BY-NC-4.0", x: 174.1, y: 93.7, z: 167.2 },
  { slug: "archive-web-crawl", name: "Archive Web Crawl", publisher: "LAION", platform: "huggingface", coverageTotal: 22, coverageBand: "minimal", sizeRows: 33082, license: "MIT", x: 90.8, y: 98.0, z: 212.8 },
  { slug: "corpus-law-abstracts", name: "Corpus Law Abstracts", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 55, coverageBand: "partial", sizeRows: 82685429, license: "CC-BY-NC-4.0", x: -184.6, y: 51.1, z: -38.0 },
  { slug: "common-multi-mini", name: "Common Multi Mini", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 41, coverageBand: "partial", sizeRows: 25654259, license: "CC-BY-SA-4.0", x: -182.5, y: -39.8, z: 68.4 },
  { slug: "pile-fin-xl", name: "Pile Fin Xl", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 26, coverageBand: "minimal", sizeRows: 3663, license: "CC0-1.0", x: -192.8, y: 57.6, z: 182.4 },
  { slug: "open-audio-dialogue", name: "Open Audio Dialogue", publisher: "Together AI", platform: "huggingface", coverageTotal: 63, coverageBand: "partial", sizeRows: 4544, license: "Not stated", x: -251.8, y: -69.5, z: -98.8 },
  { slug: "ledger-bio-captions", name: "Ledger Bio Captions", publisher: "MLCommons", platform: "direct", coverageTotal: 84, coverageBand: "extensive", sizeRows: 320744114, license: "Not stated", x: -221.6, y: -15.4, z: -258.4 },
  { slug: "ledger-multi-reviews", name: "Ledger Multi Reviews", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 9, coverageBand: "minimal", sizeRows: 10313, license: "Apache-2.0", x: -85.1, y: -31.2, z: 311.6 },
  { slug: "beacon-image-filings", name: "Beacon Image Filings", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 31, coverageBand: "minimal", sizeRows: 97761, license: "CC0-1.0", x: -107.9, y: -75.6, z: 144.4 },
  { slug: "beacon-multi-v2", name: "Beacon Multi V2", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 72, coverageBand: "partial", sizeRows: 42701, license: "ODC-By-1.0", x: 115.4, y: -13.1, z: -167.2 },
  { slug: "beacon-bio-instruct", name: "Beacon Bio Instruct", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 25, coverageBand: "minimal", sizeRows: 1426, license: "ODC-By-1.0", x: 267.3, y: -15.7, z: 190.0 },
  { slug: "strata-law-pairs", name: "Strata Law Pairs", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 62, coverageBand: "partial", sizeRows: 1745713, license: "Apache-2.0", x: 113.5, y: -61.4, z: -91.2 },
  { slug: "atlas-math-subset", name: "Atlas Math Subset", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 25, coverageBand: "minimal", sizeRows: 37018745, license: "CC-BY-4.0", x: 228.8, y: 88.5, z: 190.0 },
  { slug: "lattice-multi-captions", name: "Lattice Multi Captions", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 86, coverageBand: "extensive", sizeRows: 172385, license: "Not stated", x: 171.0, y: 34.1, z: -273.6 },
  { slug: "lattice-audio-reviews", name: "Lattice Audio Reviews", publisher: "BigScience", platform: "huggingface", coverageTotal: 20, coverageBand: "minimal", sizeRows: 46937, license: "CC-BY-SA-4.0", x: 173.7, y: 13.9, z: 228.0 },
  { slug: "pile-math-abstracts", name: "Pile Math Abstracts", publisher: "LAION", platform: "huggingface", coverageTotal: 54, coverageBand: "partial", sizeRows: 500696726, license: "MIT", x: -17.2, y: 92.5, z: -30.4 },
  { slug: "lattice-news-instruct", name: "Lattice News Instruct", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 59, coverageBand: "partial", sizeRows: 1586, license: "Not stated", x: 9.7, y: 79.3, z: -68.4 },
  { slug: "stack-chat-reviews", name: "Stack Chat Reviews", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 65, coverageBand: "partial", sizeRows: 988363, license: "BSD-3-Clause", x: -223.6, y: 65.1, z: -114.0 },
  { slug: "mesh-audio-xl", name: "Mesh Audio Xl", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 86, coverageBand: "extensive", sizeRows: 300476762, license: "CC0-1.0", x: -204.3, y: -39.1, z: -273.6 },
  { slug: "open-code-xl", name: "Open Code Xl", publisher: "Together AI", platform: "huggingface", coverageTotal: 46, coverageBand: "partial", sizeRows: 136045, license: "ODC-By-1.0", x: -78.8, y: -48.9, z: 30.4 },
  { slug: "atlas-chat-subset", name: "Atlas Chat Subset", publisher: "MLCommons", platform: "direct", coverageTotal: 64, coverageBand: "partial", sizeRows: 82125923, license: "CC-BY-SA-4.0", x: -36.8, y: -62.6, z: -106.4 },
  { slug: "archive-bio-pairs", name: "Archive Bio Pairs", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 73, coverageBand: "partial", sizeRows: 6752079, license: "BSD-3-Clause", x: -36.5, y: -72.8, z: -174.8 },
  { slug: "strata-image-reviews", name: "Strata Image Reviews", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 99, coverageBand: "extensive", sizeRows: 88405, license: "Apache-2.0", x: -86.6, y: -13.4, z: -372.4 },
  { slug: "mesh-math-v2", name: "Mesh Math V2", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 65, coverageBand: "partial", sizeRows: 48806, license: "CC0-1.0", x: -59.1, y: -87.0, z: -114.0 },
  { slug: "lattice-multi-instruct", name: "Lattice Multi Instruct", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 92, coverageBand: "extensive", sizeRows: 2385546, license: "ODC-By-1.0", x: 324.3, y: -62.9, z: -319.2 },
  { slug: "beacon-web-dialogue", name: "Beacon Web Dialogue", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 85, coverageBand: "extensive", sizeRows: 149441, license: "MIT", x: 268.7, y: -76.4, z: -266.0 },
  { slug: "quarry-chat-crawl", name: "Quarry Chat Crawl", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 21, coverageBand: "minimal", sizeRows: 678964, license: "CC-BY-SA-4.0", x: 181.3, y: 55.3, z: 220.4 },
  { slug: "corpus-news-dedup", name: "Corpus News Dedup", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 66, coverageBand: "partial", sizeRows: 2401, license: "CC-BY-NC-4.0", x: 192.5, y: 26.0, z: -121.6 },
  { slug: "archive-code-crawl", name: "Archive Code Crawl", publisher: "BigScience", platform: "huggingface", coverageTotal: 16, coverageBand: "minimal", sizeRows: 1320, license: "BSD-3-Clause", x: 141.3, y: -5.7, z: 258.4 },
  { slug: "beacon-audio-captions", name: "Beacon Audio Captions", publisher: "LAION", platform: "huggingface", coverageTotal: 44, coverageBand: "partial", sizeRows: 60314539, license: "CC-BY-4.0", x: -21.5, y: 153.7, z: 45.6 },
  { slug: "beacon-audio-subset", name: "Beacon Audio Subset", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 43, coverageBand: "partial", sizeRows: 8103, license: "CC-BY-4.0", x: -20.2, y: 141.0, z: 53.2 },
  { slug: "quarry-image-pairs", name: "Quarry Image Pairs", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 63, coverageBand: "partial", sizeRows: 27730285, license: "BSD-3-Clause", x: -247.3, y: 39.5, z: -98.8 },
  { slug: "mesh-image-pairs", name: "Mesh Image Pairs", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 48, coverageBand: "partial", sizeRows: 5963, license: "Apache-2.0", x: -289.4, y: -33.2, z: 15.2 },
  { slug: "stack-news-instruct", name: "Stack News Instruct", publisher: "Together AI", platform: "huggingface", coverageTotal: 81, coverageBand: "extensive", sizeRows: 10700746, license: "CC-BY-4.0", x: -183.9, y: 4.2, z: -235.6 },
  { slug: "pile-edu-abstracts", name: "Pile Edu Abstracts", publisher: "MLCommons", platform: "direct", coverageTotal: 30, coverageBand: "minimal", sizeRows: 18267, license: "CC-BY-NC-4.0", x: -156.5, y: -9.8, z: 152.0 },
  { slug: "mesh-image-abstracts", name: "Mesh Image Abstracts", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 49, coverageBand: "partial", sizeRows: 345411, license: "Not stated", x: -186.8, y: -99.4, z: 7.6 },
  { slug: "beacon-math-filings", name: "Beacon Math Filings", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 91, coverageBand: "extensive", sizeRows: 311885193, license: "Apache-2.0", x: -125.2, y: -79.3, z: -311.6 },
  { slug: "open-fin-subset", name: "Open Fin Subset", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 8, coverageBand: "minimal", sizeRows: 4323, license: "CC-BY-4.0", x: -42.5, y: -38.3, z: 319.2 },
  { slug: "open-code-abstracts", name: "Open Code Abstracts", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 87, coverageBand: "extensive", sizeRows: 172361249, license: "MIT", x: 303.6, y: -11.9, z: -281.2 },
  { slug: "atlas-math-mini", name: "Atlas Math Mini", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 72, coverageBand: "partial", sizeRows: 234992816, license: "BSD-3-Clause", x: 168.0, y: 5.3, z: -167.2 },
  { slug: "archive-law-pairs", name: "Archive Law Pairs", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 42, coverageBand: "partial", sizeRows: 137917, license: "CC-BY-4.0", x: 152.7, y: 26.3, z: 60.8 },
  { slug: "quarry-news-dedup", name: "Quarry News Dedup", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 14, coverageBand: "minimal", sizeRows: 10452449, license: "CC-BY-NC-4.0", x: 212.0, y: 64.5, z: 273.6 },
  { slug: "archive-math-instruct", name: "Archive Math Instruct", publisher: "BigScience", platform: "huggingface", coverageTotal: 91, coverageBand: "extensive", sizeRows: 184224, license: "Apache-2.0", x: 188.8, y: 53.0, z: -311.6 },
  { slug: "atlas-code-dedup", name: "Atlas Code Dedup", publisher: "LAION", platform: "huggingface", coverageTotal: 11, coverageBand: "minimal", sizeRows: 1098676, license: "Apache-2.0", x: 11.0, y: 33.0, z: 296.4 },
  { slug: "stack-code-subset", name: "Stack Code Subset", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 43, coverageBand: "partial", sizeRows: 294272840, license: "ODC-By-1.0", x: -159.8, y: 107.3, z: 53.2 },
  { slug: "lattice-bio-captions", name: "Lattice Bio Captions", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 22, coverageBand: "minimal", sizeRows: 1859, license: "CC-BY-SA-4.0", x: -144.7, y: -16.7, z: 212.8 },
  { slug: "atlas-bio-filings", name: "Atlas Bio Filings", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 27, coverageBand: "minimal", sizeRows: 45903866, license: "CC-BY-4.0", x: -92.6, y: 25.0, z: 174.8 },
  { slug: "mesh-fin-subset", name: "Mesh Fin Subset", publisher: "Together AI", platform: "huggingface", coverageTotal: 85, coverageBand: "extensive", sizeRows: 13551, license: "BSD-3-Clause", x: -220.7, y: 42.9, z: -266.0 },
  { slug: "corpus-chat-curated", name: "Corpus Chat Curated", publisher: "MLCommons", platform: "direct", coverageTotal: 56, coverageBand: "partial", sizeRows: 190017, license: "BSD-3-Clause", x: -45.5, y: -2.4, z: -45.6 },
  { slug: "archive-web-transcripts", name: "Archive Web Transcripts", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 25, coverageBand: "minimal", sizeRows: 202742, license: "CC-BY-4.0", x: -227.9, y: -122.6, z: 190.0 },
  { slug: "common-fin-reviews", name: "Common Fin Reviews", publisher: "Wikimedia Foundation", platform: "direct", coverageTotal: 65, coverageBand: "partial", sizeRows: 1426219, license: "MIT", x: 8.3, y: -26.5, z: -114.0 },
  { slug: "strata-edu-crawl", name: "Strata Edu Crawl", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 20, coverageBand: "minimal", sizeRows: 89411, license: "CC-BY-SA-4.0", x: -78.6, y: -15.5, z: 228.0 },
  { slug: "index-math-transcripts", name: "Index Math Transcripts", publisher: "OpenSlate Labs", platform: "github", coverageTotal: 45, coverageBand: "partial", sizeRows: 60523962, license: "CC-BY-NC-4.0", x: 197.4, y: -119.6, z: 38.0 },
  { slug: "ledger-fin-dedup", name: "Ledger Fin Dedup", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 32, coverageBand: "minimal", sizeRows: 1600, license: "BSD-3-Clause", x: 154.1, y: -33.1, z: 136.8 },
  { slug: "quarry-fin-dialogue", name: "Quarry Fin Dialogue", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 50, coverageBand: "partial", sizeRows: 6410, license: "CC-BY-4.0", x: 204.1, y: -86.2, z: 0.0 },
  { slug: "mesh-code-dedup", name: "Mesh Code Dedup", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 57, coverageBand: "partial", sizeRows: 93486173, license: "MIT", x: 194.7, y: 26.2, z: -53.2 },
  { slug: "atlas-web-dedup", name: "Atlas Web Dedup", publisher: "BigScience", platform: "huggingface", coverageTotal: 27, coverageBand: "minimal", sizeRows: 39708410, license: "CC-BY-4.0", x: 144.2, y: 20.9, z: 174.8 },
  { slug: "strata-image-curated", name: "Strata Image Curated", publisher: "LAION", platform: "huggingface", coverageTotal: 53, coverageBand: "partial", sizeRows: 3429693, license: "CC-BY-4.0", x: 12.3, y: 85.5, z: -22.8 },
  { slug: "mesh-fin-abstracts", name: "Mesh Fin Abstracts", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 88, coverageBand: "extensive", sizeRows: 11125, license: "CC-BY-SA-4.0", x: -174.9, y: 76.2, z: -288.8 },
  { slug: "ledger-bio-xl", name: "Ledger Bio Xl", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 78, coverageBand: "extensive", sizeRows: 80363138, license: "BSD-3-Clause", x: -230.9, y: -47.2, z: -212.8 },
  { slug: "corpus-math-captions", name: "Corpus Math Captions", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 98, coverageBand: "extensive", sizeRows: 46048996, license: "Apache-2.0", x: -201.1, y: 4.6, z: -364.8 },
  { slug: "corpus-fin-transcripts", name: "Corpus Fin Transcripts", publisher: "Together AI", platform: "huggingface", coverageTotal: 45, coverageBand: "partial", sizeRows: 376385456, license: "Apache-2.0", x: -181.7, y: 70.8, z: 38.0 },
  ],
  edges: [
  { a: "mesh-law-dialogue", b: "atlas-chat-pairs", kind: "declared" },
  { a: "quarry-audio-subset", b: "open-edu-v2", kind: "declared" },
  { a: "quarry-code-captions", b: "lattice-code-subset", kind: "declared" },
  { a: "stack-image-pairs", b: "mesh-fin-subset", kind: "declared" },
  { a: "pile-bio-v2", b: "lattice-bio-captions", kind: "declared" },
  { a: "strata-multi-instruct", b: "ledger-multi-reviews", kind: "declared" },
  { a: "index-bio-transcripts", b: "atlas-multi-mini", kind: "declared" },
  { a: "open-math-captions", b: "strata-bio-dedup", kind: "declared" },
  { a: "atlas-code-xl", b: "lattice-multi-captions", kind: "declared" },
  { a: "mesh-math-dedup", b: "mesh-code-crawl", kind: "declared" },
  { a: "atlas-image-xl", b: "pile-math-abstracts", kind: "declared" },
  { a: "quarry-image-v2", b: "quarry-bio-dialogue", kind: "declared" },
  { a: "open-web-transcripts", b: "stack-edu-transcripts", kind: "declared" },
  { a: "archive-code-abstracts", b: "stack-fin-crawl", kind: "declared" },
  { a: "atlas-multi-mini", b: "pile-fin-xl", kind: "declared" },
  { a: "strata-image-filings", b: "ledger-fin-dedup", kind: "declared" },
  { a: "open-edu-v2", b: "pile-chat-dedup", kind: "declared" },
  { a: "corpus-image-dialogue", b: "pile-fin-xl", kind: "declared" },
  { a: "ledger-web-xl", b: "archive-code-abstracts", kind: "declared" },
  { a: "beacon-math-curated", b: "archive-code-abstracts", kind: "declared" },
  { a: "pile-math-captions", b: "mesh-math-v2", kind: "declared" },
  { a: "stack-bio-transcripts", b: "corpus-fin-transcripts", kind: "declared" },
  { a: "mesh-edu-subset", b: "quarry-fin-dialogue", kind: "declared" },
  { a: "strata-bio-dialogue", b: "corpus-news-dedup", kind: "declared" },
  { a: "lattice-web-mini", b: "archive-bio-pairs", kind: "declared" },
  { a: "pile-edu-instruct", b: "lattice-audio-reviews", kind: "declared" },
  { a: "strata-bio-crawl", b: "mesh-math-v2", kind: "declared" },
  { a: "lattice-fin-curated", b: "mesh-audio-xl", kind: "declared" },
  { a: "archive-web-crawl", b: "lattice-multi-instruct", kind: "declared" },
  { a: "corpus-law-abstracts", b: "atlas-web-dedup", kind: "declared" },
  { a: "common-multi-mini", b: "mesh-math-dedup", kind: "declared" },
  { a: "pile-fin-xl", b: "pile-bio-v2", kind: "declared" },
  { a: "open-audio-dialogue", b: "strata-image-filings", kind: "declared" },
  { a: "beacon-multi-v2", b: "stack-multi-reviews", kind: "declared" },
  { a: "strata-law-pairs", b: "mesh-math-v2", kind: "declared" },
  { a: "lattice-audio-reviews", b: "ledger-multi-reviews", kind: "declared" },
  { a: "pile-math-abstracts", b: "common-multi-mini", kind: "declared" },
  { a: "lattice-news-instruct", b: "index-news-transcripts", kind: "declared" },
  { a: "stack-chat-reviews", b: "open-law-reviews", kind: "declared" },
  { a: "open-code-xl", b: "mesh-bio-dedup", kind: "declared" },
  { a: "atlas-chat-subset", b: "stack-bio-transcripts", kind: "declared" },
  { a: "mesh-math-v2", b: "archive-web-crawl", kind: "declared" },
  { a: "beacon-web-dialogue", b: "atlas-math-mini", kind: "declared" },
  { a: "quarry-image-pairs", b: "corpus-law-abstracts", kind: "declared" },
  { a: "mesh-image-pairs", b: "atlas-chat-subset", kind: "declared" },
  { a: "pile-edu-abstracts", b: "mesh-bio-dedup", kind: "declared" },
  { a: "open-fin-subset", b: "beacon-math-filings", kind: "declared" },
  { a: "open-code-abstracts", b: "quarry-law-subset", kind: "declared" },
  { a: "atlas-math-mini", b: "mesh-edu-subset", kind: "declared" },
  { a: "archive-law-pairs", b: "strata-law-pairs", kind: "declared" },
  { a: "atlas-code-dedup", b: "mesh-code-dedup", kind: "declared" },
  { a: "stack-code-subset", b: "open-code-abstracts", kind: "declared" },
  { a: "lattice-bio-captions", b: "ledger-bio-xl", kind: "declared" },
  { a: "atlas-bio-filings", b: "archive-math-instruct", kind: "declared" },
  { a: "corpus-chat-curated", b: "mesh-math-dedup", kind: "declared" },
  { a: "archive-web-transcripts", b: "strata-bio-dialogue", kind: "declared" },
  { a: "common-fin-reviews", b: "lattice-multi-captions", kind: "declared" },
  { a: "strata-edu-crawl", b: "atlas-chat-pairs", kind: "declared" },
  { a: "index-math-transcripts", b: "ledger-fin-dedup", kind: "declared" },
  { a: "quarry-fin-dialogue", b: "pile-web-dedup", kind: "declared" },
  { a: "ledger-bio-xl", b: "mesh-code-dedup", kind: "declared" },
  { a: "corpus-math-curated", b: "pile-bio-v2", kind: "publisher" },
  { a: "pile-bio-v2", b: "atlas-image-xl", kind: "publisher" },
  { a: "atlas-image-xl", b: "common-chat-captions", kind: "publisher" },
  { a: "common-chat-captions", b: "lattice-fin-curated", kind: "publisher" },
  { a: "lattice-fin-curated", b: "atlas-math-subset", kind: "publisher" },
  { a: "atlas-math-subset", b: "quarry-chat-crawl", kind: "publisher" },
  { a: "quarry-chat-crawl", b: "archive-law-pairs", kind: "publisher" },
  { a: "archive-law-pairs", b: "quarry-fin-dialogue", kind: "publisher" },
  { a: "open-law-reviews", b: "strata-multi-instruct", kind: "publisher" },
  { a: "strata-multi-instruct", b: "mesh-bio-dedup", kind: "publisher" },
  { a: "mesh-bio-dedup", b: "stack-bio-transcripts", kind: "publisher" },
  { a: "stack-bio-transcripts", b: "stack-fin-crawl", kind: "publisher" },
  { a: "stack-fin-crawl", b: "lattice-multi-captions", kind: "publisher" },
  { a: "lattice-multi-captions", b: "corpus-news-dedup", kind: "publisher" },
  { a: "corpus-news-dedup", b: "quarry-news-dedup", kind: "publisher" },
  { a: "quarry-news-dedup", b: "mesh-code-dedup", kind: "publisher" },
  { a: "atlas-chat-pairs", b: "pile-edu-curated", kind: "publisher" },
  { a: "pile-edu-curated", b: "quarry-image-v2", kind: "publisher" },
  { a: "quarry-image-v2", b: "mesh-edu-subset", kind: "publisher" },
  { a: "mesh-edu-subset", b: "lattice-code-subset", kind: "publisher" },
  { a: "lattice-code-subset", b: "lattice-audio-reviews", kind: "publisher" },
  { a: "lattice-audio-reviews", b: "archive-code-crawl", kind: "publisher" },
  { a: "archive-code-crawl", b: "archive-math-instruct", kind: "publisher" },
  { a: "archive-math-instruct", b: "atlas-web-dedup", kind: "publisher" },
  { a: "mesh-law-dialogue", b: "strata-law-curated", kind: "publisher" },
  { a: "strata-law-curated", b: "open-web-transcripts", kind: "publisher" },
  { a: "open-web-transcripts", b: "corpus-audio-reviews", kind: "publisher" },
  { a: "corpus-audio-reviews", b: "archive-web-crawl", kind: "publisher" },
  { a: "archive-web-crawl", b: "pile-math-abstracts", kind: "publisher" },
  { a: "pile-math-abstracts", b: "beacon-audio-captions", kind: "publisher" },
  { a: "beacon-audio-captions", b: "atlas-code-dedup", kind: "publisher" },
  { a: "atlas-code-dedup", b: "strata-image-curated", kind: "publisher" },
  { a: "ledger-multi-dedup", b: "index-bio-transcripts", kind: "publisher" },
  { a: "index-bio-transcripts", b: "index-law-dedup", kind: "publisher" },
  { a: "index-law-dedup", b: "strata-bio-dialogue", kind: "publisher" },
  { a: "strata-bio-dialogue", b: "corpus-law-abstracts", kind: "publisher" },
  { a: "corpus-law-abstracts", b: "lattice-news-instruct", kind: "publisher" },
  { a: "lattice-news-instruct", b: "beacon-audio-subset", kind: "publisher" },
  { a: "beacon-audio-subset", b: "stack-code-subset", kind: "publisher" },
  { a: "stack-code-subset", b: "mesh-fin-abstracts", kind: "publisher" },
  { a: "quarry-audio-subset", b: "open-math-captions", kind: "publisher" },
  { a: "open-math-captions", b: "archive-code-abstracts", kind: "publisher" },
  { a: "archive-code-abstracts", b: "quarry-bio-dialogue", kind: "publisher" },
  { a: "quarry-bio-dialogue", b: "common-multi-mini", kind: "publisher" },
  { a: "common-multi-mini", b: "stack-chat-reviews", kind: "publisher" },
  { a: "stack-chat-reviews", b: "quarry-image-pairs", kind: "publisher" },
  { a: "quarry-image-pairs", b: "lattice-bio-captions", kind: "publisher" },
  { a: "pile-chat-dedup", b: "common-math-xl", kind: "publisher" },
  { a: "common-math-xl", b: "atlas-multi-mini", kind: "publisher" },
  { a: "atlas-multi-mini", b: "mesh-code-crawl", kind: "publisher" },
  { a: "mesh-code-crawl", b: "pile-fin-xl", kind: "publisher" },
  { a: "pile-fin-xl", b: "mesh-audio-xl", kind: "publisher" },
  { a: "mesh-audio-xl", b: "mesh-image-pairs", kind: "publisher" },
  { a: "mesh-image-pairs", b: "atlas-bio-filings", kind: "publisher" },
  { a: "atlas-bio-filings", b: "corpus-math-captions", kind: "publisher" },
  { a: "strata-bio-dedup", b: "atlas-code-xl", kind: "publisher" },
  { a: "atlas-code-xl", b: "strata-image-filings", kind: "publisher" },
  { a: "strata-image-filings", b: "beacon-edu-mini", kind: "publisher" },
  { a: "beacon-edu-mini", b: "open-audio-dialogue", kind: "publisher" },
  { a: "open-audio-dialogue", b: "open-code-xl", kind: "publisher" },
  { a: "open-code-xl", b: "stack-news-instruct", kind: "publisher" },
  { a: "stack-news-instruct", b: "mesh-fin-subset", kind: "publisher" },
  { a: "mesh-fin-subset", b: "corpus-fin-transcripts", kind: "publisher" },
  { a: "index-news-transcripts", b: "pile-web-dedup", kind: "publisher" },
  { a: "pile-web-dedup", b: "open-edu-v2", kind: "publisher" },
  { a: "open-edu-v2", b: "stack-edu-transcripts", kind: "publisher" },
  { a: "stack-edu-transcripts", b: "ledger-bio-captions", kind: "publisher" },
  { a: "ledger-bio-captions", b: "atlas-chat-subset", kind: "publisher" },
  { a: "atlas-chat-subset", b: "pile-edu-abstracts", kind: "publisher" },
  { a: "pile-edu-abstracts", b: "corpus-chat-curated", kind: "publisher" },
  { a: "quarry-code-captions", b: "mesh-math-dedup", kind: "publisher" },
  { a: "mesh-math-dedup", b: "corpus-image-dialogue", kind: "publisher" },
  { a: "corpus-image-dialogue", b: "quarry-audio-dedup", kind: "publisher" },
  { a: "quarry-audio-dedup", b: "ledger-multi-reviews", kind: "publisher" },
  { a: "ledger-multi-reviews", b: "archive-bio-pairs", kind: "publisher" },
  { a: "archive-bio-pairs", b: "mesh-image-abstracts", kind: "publisher" },
  { a: "mesh-image-abstracts", b: "archive-web-transcripts", kind: "publisher" },
  { a: "stack-image-pairs", b: "quarry-law-subset", kind: "publisher" },
  { a: "quarry-law-subset", b: "ledger-web-xl", kind: "publisher" },
  { a: "ledger-web-xl", b: "lattice-web-mini", kind: "publisher" },
  { a: "lattice-web-mini", b: "beacon-image-filings", kind: "publisher" },
  { a: "beacon-image-filings", b: "strata-image-reviews", kind: "publisher" },
  { a: "strata-image-reviews", b: "beacon-math-filings", kind: "publisher" },
  { a: "beacon-math-filings", b: "common-fin-reviews", kind: "publisher" },
  { a: "atlas-multi-curated", b: "strata-bio-captions", kind: "publisher" },
  { a: "strata-bio-captions", b: "lattice-image-captions", kind: "publisher" },
  { a: "lattice-image-captions", b: "stack-web-pairs", kind: "publisher" },
  { a: "stack-web-pairs", b: "beacon-multi-v2", kind: "publisher" },
  { a: "beacon-multi-v2", b: "mesh-math-v2", kind: "publisher" },
  { a: "mesh-math-v2", b: "open-fin-subset", kind: "publisher" },
  { a: "open-fin-subset", b: "strata-edu-crawl", kind: "publisher" },
  { a: "stack-audio-v2", b: "stack-law-reviews", kind: "publisher" },
  { a: "stack-law-reviews", b: "beacon-math-curated", kind: "publisher" },
  { a: "beacon-math-curated", b: "pile-edu-instruct", kind: "publisher" },
  { a: "pile-edu-instruct", b: "beacon-bio-instruct", kind: "publisher" },
  { a: "beacon-bio-instruct", b: "lattice-multi-instruct", kind: "publisher" },
  { a: "lattice-multi-instruct", b: "open-code-abstracts", kind: "publisher" },
  { a: "open-code-abstracts", b: "index-math-transcripts", kind: "publisher" },
  { a: "ledger-web-mini", b: "stack-multi-reviews", kind: "publisher" },
  { a: "stack-multi-reviews", b: "pile-math-captions", kind: "publisher" },
  { a: "pile-math-captions", b: "strata-bio-crawl", kind: "publisher" },
  { a: "strata-bio-crawl", b: "strata-law-pairs", kind: "publisher" },
  { a: "strata-law-pairs", b: "beacon-web-dialogue", kind: "publisher" },
  { a: "atlas-math-mini", b: "ledger-fin-dedup", kind: "publisher" },
  { a: "corpus-math-curated", b: "index-bio-transcripts", kind: "domain" },
  { a: "strata-bio-dedup", b: "atlas-code-dedup", kind: "domain" },
  { a: "index-news-transcripts", b: "index-math-transcripts", kind: "domain" },
  { a: "stack-image-pairs", b: "stack-law-reviews", kind: "domain" },
  { a: "atlas-multi-curated", b: "mesh-bio-dedup", kind: "domain" },
  { a: "strata-multi-instruct", b: "stack-web-pairs", kind: "domain" },
  { a: "strata-multi-instruct", b: "pile-math-abstracts", kind: "domain" },
  { a: "index-bio-transcripts", b: "common-chat-captions", kind: "domain" },
  { a: "index-bio-transcripts", b: "atlas-math-subset", kind: "domain" },
  { a: "open-math-captions", b: "atlas-bio-filings", kind: "domain" },
  { a: "open-math-captions", b: "corpus-math-captions", kind: "domain" },
  { a: "strata-bio-captions", b: "beacon-edu-mini", kind: "domain" },
  { a: "atlas-image-xl", b: "ledger-fin-dedup", kind: "domain" },
  { a: "archive-code-abstracts", b: "mesh-image-abstracts", kind: "domain" },
  { a: "ledger-web-xl", b: "strata-image-reviews", kind: "domain" },
  { a: "lattice-image-captions", b: "archive-bio-pairs", kind: "domain" },
  { a: "pile-math-captions", b: "archive-web-transcripts", kind: "domain" },
  { a: "stack-bio-transcripts", b: "lattice-multi-captions", kind: "domain" },
  { a: "quarry-bio-dialogue", b: "corpus-fin-transcripts", kind: "domain" },
  { a: "atlas-math-subset", b: "lattice-multi-instruct", kind: "domain" },
  { a: "atlas-math-subset", b: "atlas-math-mini", kind: "domain" },
  { a: "pile-math-abstracts", b: "archive-math-instruct", kind: "domain" },
  { a: "atlas-chat-subset", b: "quarry-chat-crawl", kind: "domain" },
  { a: "archive-bio-pairs", b: "corpus-news-dedup", kind: "domain" },
  { a: "lattice-multi-instruct", b: "ledger-fin-dedup", kind: "domain" },
  { a: "beacon-web-dialogue", b: "mesh-image-abstracts", kind: "domain" },
  { a: "corpus-news-dedup", b: "pile-edu-abstracts", kind: "domain" },
  { a: "lattice-bio-captions", b: "ledger-fin-dedup", kind: "domain" },
  ],
  nodeCount: 120,
  platformCount: 5,
};
