/**
 * Delisted fixture — frontend-only stand-in.
 *
 * No delisting data exists in the catalog yet: there is no status-history
 * table, and nothing persists a last-confirmed date or an end state. Every
 * field here is invented so the surface could be built and verified ahead of
 * the schema.
 *
 * Two properties are load-bearing and must survive any regeneration:
 *
 *  1. dependentModels / dependentPapers are null throughout. The ingestion that
 *     would produce them (parsing model cards and papers for dataset
 *     references) does not exist. Do not populate them with plausible numbers
 *     to make the downstream filaments demoable. The empty socket is the point.
 *
 *  2. coverageTotal is COMPUTED from checksAtLastCheck with the real
 *     computeCoverage arithmetic, not asserted alongside it. A fixture whose
 *     headline figure disagrees with its own checks would teach the UI to
 *     tolerate that disagreement.
 *
 * Generated deterministically. Replace wholesale when wired to live data:
 * nothing in src/components/graveyard reads this module directly.
 */
import type { DelistedField } from './types';

export const DELISTED_FIXTURE: DelistedField = {
  records: [
  { slug: "quarry-wiki-tagged", name: "Quarry Wiki Tagged", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 46, coverageBand: "partial", license: "Not stated", sizeRows: 39468208, versions: 1, checksAtLastCheck: "nnndnnnrndrnddndnrdrddnrrndd", endState: "superseded", firstObserved: "2019-07-20", lastConfirmed: "2021-03-20", consecutiveFailures: 0, supersededBy: "relay-web-abstracts", dependentModels: null, dependentPapers: null },
  { slug: "vault-bio-mini", name: "Vault Bio Mini", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 77, coverageBand: "extensive", license: "BSD-3-Clause", sizeRows: 554322438, versions: 5, checksAtLastCheck: "nnnddddndrdddnrdrddddddddddd", endState: "superseded", firstObserved: "2021-10-04", lastConfirmed: "2022-09-04", consecutiveFailures: 0, supersededBy: "marrow-patent-tagged", dependentModels: null, dependentPapers: null },
  { slug: "pile-civic-v2", name: "Pile Civic V2", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", license: "Apache-2.0", sizeRows: 3786, versions: 11, checksAtLastCheck: "dndnrrnnnrndnnnrrdddrdndrrnn", endState: "superseded", firstObserved: "2020-02-22", lastConfirmed: "2022-09-22", consecutiveFailures: 0, supersededBy: "corpus-law-v3", dependentModels: null, dependentPapers: null },
  { slug: "tessera-edu-core", name: "Tessera Edu Core", publisher: "PyTorch Hub", platform: "github", coverageTotal: 61, coverageBand: "partial", license: "Not stated", sizeRows: 38022, versions: 9, checksAtLastCheck: "dnrnrdrdrndnddnrdnddddrdndnd", endState: "superseded", firstObserved: "2021-10-20", lastConfirmed: "2022-11-20", consecutiveFailures: 0, supersededBy: "lattice-med-core", dependentModels: null, dependentPapers: null },
  { slug: "pile-court-v3", name: "Pile Court V3", publisher: "LAION", platform: "huggingface", coverageTotal: 73, coverageBand: "partial", license: "Apache-2.0", sizeRows: 41218458, versions: 7, checksAtLastCheck: "ddrddndddddddndnnrddddnrrddr", endState: "superseded", firstObserved: "2022-04-15", lastConfirmed: "2023-11-15", consecutiveFailures: 0, supersededBy: "quarry-video-filtered", dependentModels: null, dependentPapers: null },
  { slug: "lattice-civic-mini", name: "Lattice Civic Mini", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 68, coverageBand: "partial", license: "Custom terms", sizeRows: 20966394, versions: 11, checksAtLastCheck: "dddddrdndnrrrdnddnnrdrdndddd", endState: "superseded", firstObserved: "2022-06-04", lastConfirmed: "2025-01-04", consecutiveFailures: 0, supersededBy: "corpus-web-corpus", dependentModels: null, dependentPapers: null },
  { slug: "cairn-fin-raw", name: "Cairn Fin Raw", publisher: "ETH Zurich", platform: "academic", coverageTotal: 50, coverageBand: "partial", license: "GPL-3.0", sizeRows: 366594231, versions: 3, checksAtLastCheck: "nrdrrnndrdrndrdnnndnrnnddrdd", endState: "superseded", firstObserved: "2022-02-12", lastConfirmed: "2025-04-12", consecutiveFailures: 0, supersededBy: "ledger-web-instruct", dependentModels: null, dependentPapers: null },
  { slug: "cinder-recipe-subset", name: "Cinder Recipe Subset", publisher: "Papers With Code", platform: "github", coverageTotal: 34, coverageBand: "minimal", license: "CC-BY-4.0", sizeRows: 1227310, versions: 10, checksAtLastCheck: "dnndndnnrrrnnnndddrnnnnrdnnn", endState: "superseded", firstObserved: "2023-04-07", lastConfirmed: "2025-05-07", consecutiveFailures: 0, supersededBy: "kiln-news-subset", dependentModels: null, dependentPapers: null },
  { slug: "beacon-video-dedup", name: "Beacon Video Dedup", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 38, coverageBand: "minimal", license: "CC-BY-NC-4.0", sizeRows: 392118, versions: 1, checksAtLastCheck: "dnndndddnnnnnnrrnrnddrnnndnr", endState: "superseded", firstObserved: "2025-03-25", lastConfirmed: "2025-07-25", consecutiveFailures: 0, supersededBy: "beacon-video-v3", dependentModels: null, dependentPapers: null },
  { slug: "mesh-chat-filtered", name: "Mesh Chat Filtered", publisher: "OpenDataLab", platform: "kaggle", coverageTotal: 43, coverageBand: "partial", license: "Apache-2.0", sizeRows: 378433913, versions: 11, checksAtLastCheck: "nnnnrrrdnrnnnrdnddndddndndrn", endState: "superseded", firstObserved: "2022-09-19", lastConfirmed: "2025-09-19", consecutiveFailures: 0, supersededBy: "drift-code-extended", dependentModels: null, dependentPapers: null },
  { slug: "lattice-speech-balanced", name: "Lattice Speech Balanced", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 73, coverageBand: "partial", license: "Apache-2.0", sizeRows: 448975639, versions: 8, checksAtLastCheck: "ddrrdrrrrdrdddrrrnndddddddrd", endState: "superseded", firstObserved: "2023-11-27", lastConfirmed: "2025-12-27", consecutiveFailures: 0, supersededBy: "kiln-wiki-v2", dependentModels: null, dependentPapers: null },
  { slug: "corpus-news-v3", name: "Corpus News V3", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 71, coverageBand: "partial", license: "GPL-3.0", sizeRows: 7018887, versions: 9, checksAtLastCheck: "dddrddddddnndrdrnrdnddnddddn", endState: "superseded", firstObserved: "2024-02-09", lastConfirmed: "2026-05-09", consecutiveFailures: 0, supersededBy: "mesh-fin-core", dependentModels: null, dependentPapers: null },
  { slug: "drift-court-curated", name: "Drift Court Curated", publisher: "MIT CSAIL", platform: "academic", coverageTotal: 34, coverageBand: "minimal", license: "CC-BY-NC-4.0", sizeRows: 5936534, versions: 2, checksAtLastCheck: "nndddndndnnnnnnndnnndnrndndn", endState: "superseded", firstObserved: "2024-07-25", lastConfirmed: "2026-05-25", consecutiveFailures: 0, supersededBy: "mesh-web-corpus", dependentModels: null, dependentPapers: null },
  { slug: "cairn-image-curated", name: "Cairn Image Curated", publisher: "OpenDataLab", platform: "kaggle", coverageTotal: 50, coverageBand: "partial", license: "CC0-1.0", sizeRows: 38995, versions: 11, checksAtLastCheck: "nrddnddndddnrdrddrnrnrnrrnnn", endState: "superseded", firstObserved: "2023-04-10", lastConfirmed: "2026-06-10", consecutiveFailures: 0, supersededBy: "prism-code-filtered", dependentModels: null, dependentPapers: null },
  { slug: "mesh-recipe-instruct", name: "Mesh Recipe Instruct", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 52, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 43523, versions: 8, checksAtLastCheck: "rnrnrrddnnnddnndnrndrrdddddn", endState: "gated", firstObserved: "2020-09-01", lastConfirmed: "2021-12-01", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "marrow-med-balanced", name: "Marrow Med Balanced", publisher: "MLCommons", platform: "direct", coverageTotal: 31, coverageBand: "minimal", license: "CC-BY-4.0", sizeRows: 76133, versions: 3, checksAtLastCheck: "nnnddnnrrndnnrdnnnnrnnndrrrn", endState: "gated", firstObserved: "2018-10-23", lastConfirmed: "2021-12-23", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "beacon-civic-subset", name: "Beacon Civic Subset", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 21, coverageBand: "minimal", license: "GPL-3.0", sizeRows: 56970954, versions: 10, checksAtLastCheck: "nnrnndnnnrrnnnndnrnnnnnnndnd", endState: "gated", firstObserved: "2019-03-08", lastConfirmed: "2022-03-08", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "quarry-fin-aligned", name: "Quarry Fin Aligned", publisher: "OpenDataLab", platform: "kaggle", coverageTotal: 43, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 935037088, versions: 2, checksAtLastCheck: "drnrnddrrdnnnrnrrnrrdndrnnnd", endState: "gated", firstObserved: "2019-01-10", lastConfirmed: "2022-03-10", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "marrow-court-instruct", name: "Marrow Court Instruct", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 81, coverageBand: "extensive", license: "BSD-3-Clause", sizeRows: 19734, versions: 7, checksAtLastCheck: "dddndddddddddnnnndddrddddddd", endState: "gated", firstObserved: "2019-04-15", lastConfirmed: "2022-04-15", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "tessera-wiki-corpus", name: "Tessera Wiki Corpus", publisher: "LAION", platform: "huggingface", coverageTotal: 63, coverageBand: "partial", license: "GPL-3.0", sizeRows: 425264, versions: 11, checksAtLastCheck: "rdndndrdrddnndnnxdrddddrnrdd", endState: "gated", firstObserved: "2019-06-10", lastConfirmed: "2022-06-10", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "ledger-web-instruct", name: "Ledger Web Instruct", publisher: "BigScience", platform: "huggingface", coverageTotal: 77, coverageBand: "extensive", license: "BSD-3-Clause", sizeRows: 17150200, versions: 3, checksAtLastCheck: "rddnrdrdndddrddndrddddrdddrd", endState: "gated", firstObserved: "2022-05-07", lastConfirmed: "2023-11-07", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "corpus-web-corpus", name: "Corpus Web Corpus", publisher: "OpenDataLab", platform: "kaggle", coverageTotal: 41, coverageBand: "partial", license: "CC0-1.0", sizeRows: 70968528, versions: 11, checksAtLastCheck: "ndnddnnnrddrrnndnnndnddndnnn", endState: "gated", firstObserved: "2020-10-19", lastConfirmed: "2024-01-19", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "drift-law-core", name: "Drift Law Core", publisher: "PyTorch Hub", platform: "github", coverageTotal: 45, coverageBand: "partial", license: "GPL-3.0", sizeRows: 9003598, versions: 8, checksAtLastCheck: "nnndrnddrrddnnddnrndnnnrnddn", endState: "gated", firstObserved: "2021-11-25", lastConfirmed: "2024-04-25", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "harbor-fin-aligned", name: "Harbor Fin Aligned", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", license: "CC0-1.0", sizeRows: 5967, versions: 9, checksAtLastCheck: "ddnnnddnrnndnrndndnndddnnrrn", endState: "gated", firstObserved: "2022-06-23", lastConfirmed: "2024-06-23", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "anchor-recipe-instruct", name: "Anchor Recipe Instruct", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 52, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 16781178, versions: 10, checksAtLastCheck: "dndrnnrnddrnrddndrdnrnrdnndd", endState: "gated", firstObserved: "2022-11-27", lastConfirmed: "2024-07-27", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "relay-law-instruct", name: "Relay Law Instruct", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 20, coverageBand: "minimal", license: "GPL-3.0", sizeRows: 457815, versions: 6, checksAtLastCheck: "ndnndrnndnrnnnndnnnnnnnrnnnn", endState: "gated", firstObserved: "2022-09-14", lastConfirmed: "2025-03-14", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "prism-edu-dedup", name: "Prism Edu Dedup", publisher: "Common Crawl", platform: "direct", coverageTotal: 47, coverageBand: "partial", license: "Apache-2.0", sizeRows: 93667, versions: 9, checksAtLastCheck: "dndddnrdrrnndnrddndnndrnrnnn", endState: "gated", firstObserved: "2022-11-08", lastConfirmed: "2025-04-08", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "quarry-law-core", name: "Quarry Law Core", publisher: "Common Crawl", platform: "direct", coverageTotal: 70, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 5538923, versions: 5, checksAtLastCheck: "drnrdrdndndddddrddrdrddddnnr", endState: "gated", firstObserved: "2022-03-03", lastConfirmed: "2025-05-03", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "stack-code-core", name: "Stack Code Core", publisher: "MLCommons", platform: "direct", coverageTotal: 54, coverageBand: "partial", license: "Not stated", sizeRows: 504194, versions: 6, checksAtLastCheck: "dndnddrrndnrrrddnrndndrdnrnd", endState: "gated", firstObserved: "2023-12-25", lastConfirmed: "2025-06-25", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "lattice-med-balanced", name: "Lattice Med Balanced", publisher: "Common Crawl", platform: "direct", coverageTotal: 30, coverageBand: "minimal", license: "CC0-1.0", sizeRows: 921215420, versions: 1, checksAtLastCheck: "rndnrndnnnndnnrndnrdrnndnnnn", endState: "gated", firstObserved: "2024-12-12", lastConfirmed: "2025-10-12", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "quarry-bio-raw", name: "Quarry Bio Raw", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 55, coverageBand: "partial", license: "CC0-1.0", sizeRows: 20803, versions: 7, checksAtLastCheck: "ddrnndrdnrndnnndndrdrdndrddr", endState: "gated", firstObserved: "2024-10-24", lastConfirmed: "2026-01-24", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "prism-wiki-subset", name: "Prism Wiki Subset", publisher: "Mozilla Foundation", platform: "direct", coverageTotal: 38, coverageBand: "minimal", license: "BSD-3-Clause", sizeRows: 985697, versions: 4, checksAtLastCheck: "nrnnrdnrnndnnrrddndnndnddnnn", endState: "gated", firstObserved: "2024-11-21", lastConfirmed: "2026-03-21", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "prism-speech-aligned", name: "Prism Speech Aligned", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 63, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 5818, versions: 7, checksAtLastCheck: "dnndrrrdrrndddddddrrrndnrddn", endState: "gated", firstObserved: "2023-03-04", lastConfirmed: "2026-04-04", consecutiveFailures: 0, dependentModels: null, dependentPapers: null },
  { slug: "kiln-news-subset", name: "Kiln News Subset", publisher: "MLCommons", platform: "direct", coverageTotal: 82, coverageBand: "extensive", license: "CC0-1.0", sizeRows: 65185, versions: 9, checksAtLastCheck: "dddrdddrddrdddddrdddrrrrrdrd", endState: "withdrawn", firstObserved: "2019-05-07", lastConfirmed: "2022-07-07", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "stack-court-core", name: "Stack Court Core", publisher: "LAION", platform: "huggingface", coverageTotal: 77, coverageBand: "extensive", license: "MIT", sizeRows: 4402, versions: 3, checksAtLastCheck: "drdrdddrddddrrrrxnrdddnddddd", endState: "withdrawn", firstObserved: "2020-12-08", lastConfirmed: "2022-07-08", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "tessera-code-pairs", name: "Tessera Code Pairs", publisher: "Together AI", platform: "huggingface", coverageTotal: 73, coverageBand: "partial", license: "Not stated", sizeRows: 276995452, versions: 2, checksAtLastCheck: "nddnddndrddddrddddrnddnddddn", endState: "withdrawn", firstObserved: "2020-06-06", lastConfirmed: "2022-10-06", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "atlas-genome-core", name: "Atlas Genome Core", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 57, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 617241889, versions: 3, checksAtLastCheck: "nnnndrddrddrrnrdnndndrdddrdr", endState: "withdrawn", firstObserved: "2022-07-10", lastConfirmed: "2022-11-10", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "stack-recipe-filtered", name: "Stack Recipe Filtered", publisher: "MIT CSAIL", platform: "academic", coverageTotal: 34, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 379241926, versions: 11, checksAtLastCheck: "nndddrrrrdnndrrnnnnnnnrnrnnr", endState: "withdrawn", firstObserved: "2021-02-14", lastConfirmed: "2022-12-14", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "relay-web-abstracts", name: "Relay Web Abstracts", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 81, coverageBand: "extensive", license: "BSD-3-Clause", sizeRows: 741115951, versions: 2, checksAtLastCheck: "dndddnndddnddrddddrdddrddddd", endState: "withdrawn", firstObserved: "2022-04-10", lastConfirmed: "2023-04-10", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "lattice-genome-v2", name: "Lattice Genome V2", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 63, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 457443395, versions: 8, checksAtLastCheck: "ndddddrddddrrrrnrrrnddndndnr", endState: "withdrawn", firstObserved: "2020-05-03", lastConfirmed: "2023-05-03", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "cairn-fin-dedup", name: "Cairn Fin Dedup", publisher: "Common Crawl", platform: "direct", coverageTotal: 30, coverageBand: "minimal", license: "Apache-2.0", sizeRows: 701018, versions: 8, checksAtLastCheck: "nrrnnnrnnrnnnddnnnrnrdndrdnn", endState: "withdrawn", firstObserved: "2021-06-06", lastConfirmed: "2023-10-06", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "drift-audio-dedup", name: "Drift Audio Dedup", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 32, coverageBand: "minimal", license: "MIT", sizeRows: 2199466, versions: 10, checksAtLastCheck: "nrdrnndnrrnnnnndnnrndndrrnnr", endState: "withdrawn", firstObserved: "2023-09-09", lastConfirmed: "2024-02-09", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "corpus-chat-aligned", name: "Corpus Chat Aligned", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 61, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 95631, versions: 8, checksAtLastCheck: "dndnddndnrndnddddrddddnnnrrd", endState: "withdrawn", firstObserved: "2022-11-15", lastConfirmed: "2024-03-15", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "marrow-audio-extended", name: "Marrow Audio Extended", publisher: "OpenDataLab", platform: "kaggle", coverageTotal: 63, coverageBand: "partial", license: "GPL-3.0", sizeRows: 83097, versions: 4, checksAtLastCheck: "nrrddnddddddndrrddrrdnrnndnd", endState: "withdrawn", firstObserved: "2021-10-26", lastConfirmed: "2024-03-26", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "cairn-fin-v2", name: "Cairn Fin V2", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 54, coverageBand: "partial", license: "GPL-3.0", sizeRows: 4167323, versions: 8, checksAtLastCheck: "ndrdrnrnnddrdrddrnnrndndnrdd", endState: "withdrawn", firstObserved: "2023-09-01", lastConfirmed: "2024-05-01", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "ledger-patent-instruct", name: "Ledger Patent Instruct", publisher: "MLCommons", platform: "direct", coverageTotal: 39, coverageBand: "minimal", license: "GPL-3.0", sizeRows: 83968, versions: 1, checksAtLastCheck: "nndnnnrdndrndndrrnnddndrnrnn", endState: "withdrawn", firstObserved: "2022-01-15", lastConfirmed: "2024-06-15", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "atlas-fin-dedup", name: "Atlas Fin Dedup", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 45, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 127185172, versions: 8, checksAtLastCheck: "rdnndnndndddnnrrrdnrrdrrnnrn", endState: "withdrawn", firstObserved: "2022-04-27", lastConfirmed: "2024-12-27", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "harbor-forum-extended", name: "Harbor Forum Extended", publisher: "BigScience", platform: "huggingface", coverageTotal: 68, coverageBand: "partial", license: "Custom terms", sizeRows: 3771, versions: 2, checksAtLastCheck: "rdrrrrddrrrdnddnnddddndddndd", endState: "withdrawn", firstObserved: "2023-10-20", lastConfirmed: "2025-01-20", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "corpus-law-v3", name: "Corpus Law V3", publisher: "PyTorch Hub", platform: "github", coverageTotal: 66, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 324927, versions: 9, checksAtLastCheck: "ndrrnrrddnddddddndrrddnrnddd", endState: "withdrawn", firstObserved: "2022-07-18", lastConfirmed: "2025-02-18", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "kiln-chat-core", name: "Kiln Chat Core", publisher: "MLCommons", platform: "direct", coverageTotal: 75, coverageBand: "extensive", license: "Apache-2.0", sizeRows: 36299, versions: 7, checksAtLastCheck: "rrdddddddrdnrrdrddrdnddrdddn", endState: "withdrawn", firstObserved: "2022-04-22", lastConfirmed: "2025-02-22", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "stack-wiki-tagged", name: "Stack Wiki Tagged", publisher: "BigScience", platform: "huggingface", coverageTotal: 66, coverageBand: "partial", license: "Not stated", sizeRows: 81071, versions: 1, checksAtLastCheck: "rrddnxrndrdndndddrdddndddrdn", endState: "withdrawn", firstObserved: "2023-08-13", lastConfirmed: "2025-06-13", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "drift-patent-tagged", name: "Drift Patent Tagged", publisher: "MLCommons", platform: "direct", coverageTotal: 77, coverageBand: "extensive", license: "BSD-3-Clause", sizeRows: 257551021, versions: 9, checksAtLastCheck: "ddndrrndddddrdrndrddddddnddd", endState: "withdrawn", firstObserved: "2024-06-15", lastConfirmed: "2025-10-15", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "harbor-video-extended", name: "Harbor Video Extended", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 70, coverageBand: "partial", license: "MIT", sizeRows: 494944209, versions: 11, checksAtLastCheck: "ndndrxdrrddndddddddrrrnndddd", endState: "withdrawn", firstObserved: "2023-06-08", lastConfirmed: "2025-12-08", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "stack-genome-aligned", name: "Stack Genome Aligned", publisher: "LAION", platform: "huggingface", coverageTotal: 52, coverageBand: "partial", license: "Custom terms", sizeRows: 976279584, versions: 9, checksAtLastCheck: "dnddddrnnnddndnrdnnnrdndrndr", endState: "withdrawn", firstObserved: "2023-03-04", lastConfirmed: "2026-02-04", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "prism-code-sample", name: "Prism Code Sample", publisher: "MIT CSAIL", platform: "academic", coverageTotal: 41, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 8042160, versions: 6, checksAtLastCheck: "dnnnndnnndddnrdrrnnrdrrnndnr", endState: "withdrawn", firstObserved: "2023-01-05", lastConfirmed: "2026-03-05", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "fathom-web-tagged", name: "Fathom Web Tagged", publisher: "ETH Zurich", platform: "academic", coverageTotal: 41, coverageBand: "partial", license: "CC0-1.0", sizeRows: 62714144, versions: 4, checksAtLastCheck: "nnndndrnrnddnnnrdrrrrnndrrdn", endState: "withdrawn", firstObserved: "2023-10-23", lastConfirmed: "2026-03-23", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "drift-code-extended", name: "Drift Code Extended", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 40, coverageBand: "partial", license: "GPL-3.0", sizeRows: 7494159, versions: 9, checksAtLastCheck: "nnddnnndndddrnndrnnrnndrnnnd", endState: "withdrawn", firstObserved: "2023-08-07", lastConfirmed: "2026-05-07", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "corpus-web-v2", name: "Corpus Web V2", publisher: "ETH Zurich", platform: "academic", coverageTotal: 49, coverageBand: "partial", license: "CC0-1.0", sizeRows: 278919, versions: 7, checksAtLastCheck: "dnddddrdnnrndnnnrrndndnrddnn", endState: "unreachable", firstObserved: "2019-04-20", lastConfirmed: "2021-01-20", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "mesh-fin-core", name: "Mesh Fin Core", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 52, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 78144511, versions: 2, checksAtLastCheck: "rnndndddndndrrdnddndndrrdnnn", endState: "unreachable", firstObserved: "2018-09-05", lastConfirmed: "2021-02-05", consecutiveFailures: 8, dependentModels: null, dependentPapers: null },
  { slug: "prism-fin-v3", name: "Prism Fin V3", publisher: "Kaggle Community", platform: "kaggle", coverageTotal: 95, coverageBand: "extensive", license: "MIT", sizeRows: 538357839, versions: 4, checksAtLastCheck: "ddndrddddddddddddddddddddddd", endState: "unreachable", firstObserved: "2020-07-18", lastConfirmed: "2021-11-18", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "quarry-code-corpus", name: "Quarry Code Corpus", publisher: "MLCommons", platform: "direct", coverageTotal: 39, coverageBand: "minimal", license: "BSD-3-Clause", sizeRows: 73090155, versions: 5, checksAtLastCheck: "dddnndnnnnnnndnnnnnrnrddrddr", endState: "unreachable", firstObserved: "2020-12-19", lastConfirmed: "2022-02-19", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "harbor-law-extended", name: "Harbor Law Extended", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 40, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 82175, versions: 3, checksAtLastCheck: "rnrdnndnnrnndrdnnnnndddnrrnd", endState: "unreachable", firstObserved: "2019-09-10", lastConfirmed: "2022-03-10", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "lattice-med-core", name: "Lattice Med Core", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 68, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 53470852, versions: 7, checksAtLastCheck: "dddddddndnndnndddnrddrnddndd", endState: "unreachable", firstObserved: "2019-12-10", lastConfirmed: "2022-07-10", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "kiln-wiki-v2", name: "Kiln Wiki V2", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 41, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 182483, versions: 9, checksAtLastCheck: "nrnnrrdrrdnddrrndnrdnrnnndnn", endState: "unreachable", firstObserved: "2020-02-21", lastConfirmed: "2022-11-21", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "quarry-genome-curated", name: "Quarry Genome Curated", publisher: "Papers With Code", platform: "github", coverageTotal: 70, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 94446271, versions: 4, checksAtLastCheck: "dnnrrdrrrddnrddrddrddddrrrdd", endState: "unreachable", firstObserved: "2022-02-20", lastConfirmed: "2022-12-20", consecutiveFailures: 9, dependentModels: null, dependentPapers: null },
  { slug: "beacon-video-v3", name: "Beacon Video V3", publisher: "TensorFlow Datasets", platform: "github", coverageTotal: 66, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 666875, versions: 10, checksAtLastCheck: "dnnnddnnrddddrdrdddddndnnddd", endState: "unreachable", firstObserved: "2020-12-21", lastConfirmed: "2023-03-21", consecutiveFailures: 9, dependentModels: null, dependentPapers: null },
  { slug: "corpus-wiki-abstracts", name: "Corpus Wiki Abstracts", publisher: "MLCommons", platform: "direct", coverageTotal: 34, coverageBand: "minimal", license: "CC-BY-NC-4.0", sizeRows: 23674677, versions: 7, checksAtLastCheck: "ndndrdnrdrrrnnnrdnnrnrnnrnnn", endState: "unreachable", firstObserved: "2020-01-09", lastConfirmed: "2023-04-09", consecutiveFailures: 11, dependentModels: null, dependentPapers: null },
  { slug: "kiln-law-corpus", name: "Kiln Law Corpus", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 47, coverageBand: "partial", license: "GPL-3.0", sizeRows: 23512, versions: 4, checksAtLastCheck: "nnddnddndndrdrnrndnrnrnrnndd", endState: "unreachable", firstObserved: "2020-10-10", lastConfirmed: "2023-05-10", consecutiveFailures: 9, dependentModels: null, dependentPapers: null },
  { slug: "kiln-law-filtered", name: "Kiln Law Filtered", publisher: "ETH Zurich", platform: "academic", coverageTotal: 43, coverageBand: "partial", license: "GPL-3.0", sizeRows: 379407, versions: 7, checksAtLastCheck: "nnnnrndrnnndrndnnnddnddrddrr", endState: "unreachable", firstObserved: "2022-09-02", lastConfirmed: "2023-09-02", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "stack-code-subset", name: "Stack Code Subset", publisher: "MLCommons", platform: "direct", coverageTotal: 34, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 97659215, versions: 9, checksAtLastCheck: "ndrnnnrdnnrnnnnnnrnnrdndrrdd", endState: "unreachable", firstObserved: "2021-04-02", lastConfirmed: "2023-10-02", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "mesh-web-corpus", name: "Mesh Web Corpus", publisher: "LAION", platform: "huggingface", coverageTotal: 54, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 2233, versions: 9, checksAtLastCheck: "ddnrdrnndrddrnnnrrdrnddrnrdr", endState: "unreachable", firstObserved: "2022-11-15", lastConfirmed: "2023-11-15", consecutiveFailures: 9, dependentModels: null, dependentPapers: null },
  { slug: "harbor-audio-filtered", name: "Harbor Audio Filtered", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 81, coverageBand: "extensive", license: "ODC-By-1.0", sizeRows: 7499508, versions: 8, checksAtLastCheck: "rdrrdrrdddddrdrdddrdrdnddddd", endState: "unreachable", firstObserved: "2021-04-07", lastConfirmed: "2023-12-07", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "cairn-web-instruct", name: "Cairn Web Instruct", publisher: "TensorFlow Datasets", platform: "github", coverageTotal: 74, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 53988882, versions: 10, checksAtLastCheck: "dnddddnddddnddrrxrdrrddnddrd", endState: "unreachable", firstObserved: "2022-02-18", lastConfirmed: "2023-12-18", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "fathom-code-sample", name: "Fathom Code Sample", publisher: "TensorFlow Datasets", platform: "github", coverageTotal: 50, coverageBand: "partial", license: "Not stated", sizeRows: 880012, versions: 9, checksAtLastCheck: "ddnnrdnddrdndrddnrrnrnnndrnr", endState: "unreachable", firstObserved: "2023-02-08", lastConfirmed: "2024-01-08", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "marrow-video-sample", name: "Marrow Video Sample", publisher: "Papers With Code", platform: "github", coverageTotal: 36, coverageBand: "minimal", license: "Not stated", sizeRows: 6653125, versions: 7, checksAtLastCheck: "nnnrnrddrrnnndnnnndnnrdrnrrd", endState: "unreachable", firstObserved: "2022-06-03", lastConfirmed: "2024-05-03", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "fathom-patent-corpus", name: "Fathom Patent Corpus", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 73, coverageBand: "partial", license: "CC-BY-4.0", sizeRows: 8958017, versions: 6, checksAtLastCheck: "dndndddnddddrrddrdddrddndndr", endState: "unreachable", firstObserved: "2023-05-15", lastConfirmed: "2024-06-15", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "marrow-patent-tagged", name: "Marrow Patent Tagged", publisher: "Together AI", platform: "huggingface", coverageTotal: 72, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 850829, versions: 11, checksAtLastCheck: "rddrrnndndddrndddddrdrddrddr", endState: "unreachable", firstObserved: "2022-05-05", lastConfirmed: "2024-07-05", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "prism-code-filtered", name: "Prism Code Filtered", publisher: "NVIDIA", platform: "huggingface", coverageTotal: 45, coverageBand: "partial", license: "CC-BY-NC-4.0", sizeRows: 11045, versions: 10, checksAtLastCheck: "dnnrddddndnddnnrnnnnnndnddnr", endState: "unreachable", firstObserved: "2023-07-10", lastConfirmed: "2024-07-10", consecutiveFailures: 8, dependentModels: null, dependentPapers: null },
  { slug: "corpus-web-aligned", name: "Corpus Web Aligned", publisher: "Papers With Code", platform: "github", coverageTotal: 52, coverageBand: "partial", license: "GPL-3.0", sizeRows: 485161, versions: 3, checksAtLastCheck: "dnnrddndnnnndrnnrdddrdnrrddr", endState: "unreachable", firstObserved: "2023-10-14", lastConfirmed: "2024-08-14", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "quarry-video-filtered", name: "Quarry Video Filtered", publisher: "MLCommons", platform: "direct", coverageTotal: 47, coverageBand: "partial", license: "CC0-1.0", sizeRows: 679948968, versions: 2, checksAtLastCheck: "dndndrnnrrndrrrndnrddrnnrndr", endState: "unreachable", firstObserved: "2022-02-08", lastConfirmed: "2024-09-08", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "kiln-civic-v3", name: "Kiln Civic V3", publisher: "MLCommons", platform: "direct", coverageTotal: 27, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 6046583, versions: 1, checksAtLastCheck: "nnnnndnndnrnnnnrdndndnnnndnr", endState: "unreachable", firstObserved: "2022-03-15", lastConfirmed: "2024-09-15", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "cinder-bio-mini", name: "Cinder Bio Mini", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 72, coverageBand: "partial", license: "GPL-3.0", sizeRows: 961569541, versions: 1, checksAtLastCheck: "drdddddrdnrndddnddnnnddddrdd", endState: "unreachable", firstObserved: "2022-07-03", lastConfirmed: "2025-01-03", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "drift-recipe-subset", name: "Drift Recipe Subset", publisher: "Zenodo Archive", platform: "academic", coverageTotal: 61, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 2764104, versions: 9, checksAtLastCheck: "ddnrnddrrdndrddddrddnrndnndn", endState: "unreachable", firstObserved: "2022-11-06", lastConfirmed: "2025-03-06", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "fathom-chat-core", name: "Fathom Chat Core", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 43, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 52412, versions: 6, checksAtLastCheck: "nnndndnndrddnnnrrndndrrdndrn", endState: "unreachable", firstObserved: "2022-08-13", lastConfirmed: "2025-03-13", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "atlas-law-curated", name: "Atlas Law Curated", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 57, coverageBand: "partial", license: "Apache-2.0", sizeRows: 82015, versions: 8, checksAtLastCheck: "rnrrddnnnddrddnnrrddndnrdddr", endState: "unreachable", firstObserved: "2022-10-13", lastConfirmed: "2025-05-13", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "prism-patent-curated", name: "Prism Patent Curated", publisher: "Together AI", platform: "huggingface", coverageTotal: 55, coverageBand: "partial", license: "BSD-3-Clause", sizeRows: 9361212, versions: 9, checksAtLastCheck: "nddrdnrdndndrnddndndddnnndnd", endState: "unreachable", firstObserved: "2025-01-15", lastConfirmed: "2025-05-15", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "drift-chat-pairs", name: "Drift Chat Pairs", publisher: "Cohere For AI", platform: "huggingface", coverageTotal: 84, coverageBand: "extensive", license: "ODC-By-1.0", sizeRows: 7393328, versions: 8, checksAtLastCheck: "ddnddddddddddrdddrddrdddnrdr", endState: "unreachable", firstObserved: "2025-02-07", lastConfirmed: "2025-06-07", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "fathom-recipe-dedup", name: "Fathom Recipe Dedup", publisher: "EleutherAI", platform: "huggingface", coverageTotal: 64, coverageBand: "partial", license: "Apache-2.0", sizeRows: 52626, versions: 4, checksAtLastCheck: "dnrrdrrddrdrdnnddndnddndrrdd", endState: "unreachable", firstObserved: "2023-02-21", lastConfirmed: "2025-06-21", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "marrow-web-filtered", name: "Marrow Web Filtered", publisher: "LAION", platform: "huggingface", coverageTotal: 25, coverageBand: "minimal", license: "CC-BY-4.0", sizeRows: 4711, versions: 1, checksAtLastCheck: "ndrnrnnnnrnrnnnrndnrnnnnddnn", endState: "unreachable", firstObserved: "2024-10-02", lastConfirmed: "2025-07-02", consecutiveFailures: 10, dependentModels: null, dependentPapers: null },
  { slug: "marrow-recipe-aligned", name: "Marrow Recipe Aligned", publisher: "Allen Institute for AI", platform: "academic", coverageTotal: 64, coverageBand: "partial", license: "Apache-2.0", sizeRows: 7425905, versions: 3, checksAtLastCheck: "rddrdddnddrrrdndrndndddnrnrd", endState: "unreachable", firstObserved: "2024-01-11", lastConfirmed: "2025-10-11", consecutiveFailures: 7, dependentModels: null, dependentPapers: null },
  { slug: "marrow-recipe-sample", name: "Marrow Recipe Sample", publisher: "Stanford CRFM", platform: "academic", coverageTotal: 25, coverageBand: "minimal", license: "CC-BY-4.0", sizeRows: 6936213, versions: 3, checksAtLastCheck: "nnrnnrrnnnnnnnnndnddnrnnrndr", endState: "unreachable", firstObserved: "2024-06-26", lastConfirmed: "2025-12-26", consecutiveFailures: 3, dependentModels: null, dependentPapers: null },
  { slug: "drift-video-corpus", name: "Drift Video Corpus", publisher: "LAION", platform: "huggingface", coverageTotal: 50, coverageBand: "partial", license: "ODC-By-1.0", sizeRows: 74417136, versions: 2, checksAtLastCheck: "nnddrdrrdndrndrrdnrnddrrnnnr", endState: "unreachable", firstObserved: "2024-12-16", lastConfirmed: "2026-01-16", consecutiveFailures: 9, dependentModels: null, dependentPapers: null },
  { slug: "harbor-video-dedup", name: "Harbor Video Dedup", publisher: "Hugging Face", platform: "huggingface", coverageTotal: 20, coverageBand: "minimal", license: "CC-BY-SA-4.0", sizeRows: 595715, versions: 1, checksAtLastCheck: "nnnnnnrnnnnnrrrdnnrndnnnnndn", endState: "unreachable", firstObserved: "2023-05-15", lastConfirmed: "2026-04-15", consecutiveFailures: 5, dependentModels: null, dependentPapers: null },
  { slug: "beacon-web-curated", name: "Beacon Web Curated", publisher: "MIT CSAIL", platform: "academic", coverageTotal: 71, coverageBand: "partial", license: "CC-BY-SA-4.0", sizeRows: 643523506, versions: 1, checksAtLastCheck: "ddddnddrdnrdddnrddddrdnnnddd", endState: "unreachable", firstObserved: "2024-11-25", lastConfirmed: "2026-04-25", consecutiveFailures: 6, dependentModels: null, dependentPapers: null },
  { slug: "anchor-speech-dedup", name: "Anchor Speech Dedup", publisher: "TensorFlow Datasets", platform: "github", coverageTotal: 54, coverageBand: "partial", license: "GPL-3.0", sizeRows: 406805, versions: 1, checksAtLastCheck: "drrddnnddrdrdrnrrnddndrndnnn", endState: "unreachable", firstObserved: "2024-02-23", lastConfirmed: "2026-05-23", consecutiveFailures: 4, dependentModels: null, dependentPapers: null },
  { slug: "quarry-wiki-v2", name: "Quarry Wiki V2", publisher: "MIT CSAIL", platform: "academic", coverageTotal: 23, coverageBand: "minimal", license: "BSD-3-Clause", sizeRows: 875205, versions: 7, checksAtLastCheck: "nnnrrrnnnrdnnnrrnnnnnnnrdndn", endState: "unreachable", firstObserved: "2023-05-25", lastConfirmed: "2026-06-25", consecutiveFailures: 8, dependentModels: null, dependentPapers: null },
  ],
  total: 96,
};
